services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver_data:/var/opt/mssql
#    healthcheck:
#      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' || exit 1"]
#      interval: 10s
#      retries: 10
#      start_period: 10s
#      timeout: 3s

  todolist-api:
    image: todolist-api
    build:
      context: ./ToDoList-API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TodoList;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - CorsOrigins=http://localhost:3000
    depends_on:
      sqlserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  todolist-react:
    image: todolist-react
    build:
      context: ./todo-list-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
#      - VITE_API_BASE_URL=http://localhost:5000
      - VITE_API_BASE_URL=http://host.docker.internal:5000
    depends_on:
      - todolist-api

volumes:
  sqlserver_data: